---
- name: openvpn | Delete instance key from CA (S3)
  aws_s3:
    aws_access_key: "{{
      vars['openvpn_ca_storage_source']['aws_access_key'] | default(omit) }}"
    aws_secret_key: "{{
      vars['openvpn_ca_storage_source']['aws_secret_key'] | default(omit) }}"
    bucket: "{{ vars['openvpn_ca_storage_source']['bucket'] | default(omit) }}"
    ignore_nonexistent_bucket: "true"
    rgw: "{{ vars['openvpn_ca_storage_source']['rgw'] | default(omit) }}"
    s3_url: "{{ vars['openvpn_ca_storage_source']['s3_url'] | default(omit) }}"
    validate_certs: "{{
      vars['openvpn_ca_storage_source']['validate_certs'] | default(omit) }}"
    region: "{{ vars['openvpn_ca_storage_source']['region'] | default(omit) }}"
    profile: "{{
      vars['openvpn_ca_storage_source']['profile'] | default(omit) }}"
    mode: "delobj"
    object: "{{ '/' ~ vars['openvpn_ca_storage_source']['object_prefix'] ~ '/' ~
      vars['openvpn_instance_name'] ~ '.key' }}"
- name: openvpn | Delete instance cert from CA (S3)
  aws_s3:
    aws_access_key: "{{
      vars['openvpn_ca_storage_source']['aws_access_key'] | default(omit) }}"
    aws_secret_key: "{{
      vars['openvpn_ca_storage_source']['aws_secret_key'] | default(omit) }}"
    bucket: "{{ vars['openvpn_ca_storage_source']['bucket'] | default(omit) }}"
    ignore_nonexistent_bucket: "true"
    rgw: "{{ vars['openvpn_ca_storage_source']['rgw'] | default(omit) }}"
    s3_url: "{{ vars['openvpn_ca_storage_source']['s3_url'] | default(omit) }}"
    validate_certs: "{{
      vars['openvpn_ca_storage_source']['validate_certs'] | default(omit) }}"
    region: "{{ vars['openvpn_ca_storage_source']['region'] | default(omit) }}"
    profile: "{{
      vars['openvpn_ca_storage_source']['profile'] | default(omit) }}"
    mode: "delobj"
    object: "{{ '/' ~ vars['openvpn_ca_storage_source']['object_prefix'] ~ '/' ~
      vars['openvpn_instance_name'] ~ '.crt' }}"
